_target_: philia.models.interface_model_joint.JointInterfaceModel
lr: 0.001
wd: 1.e-5
lr_patience: 4
d_mlp: 64
weight_dihedral_loss: 0.02
weight_aug: 1.0
weight_length: 1.0
num_components: 3
interface_pred: true
freeze_embeddings: true
scale_option: scalar